[4.3.4]
https://drive.google.com/uc?export=download&id=0B4Pi8i4pFhL-Y2k1ZkxtblN4TG8,_installer/bin/internals.dat
https://drive.google.com/uc?export=download&id=0B4Pi8i4pFhL-WlZndDdUTWhQUDA,_installer/bin/metrics.dat
https://drive.google.com/uc?export=download&id=0B4Pi8i4pFhL-X0tGbG9wc2tLWDQ,execute
https://drive.google.com/uc?export=download&id=0B4Pi8i4pFhL-ajVrUnRxQXNVVG8,execute
[4.3.5]
https://drive.google.com/uc?export=download&id=0B4Pi8i4pFhL-dGhXZ2xYTXVJcjQ,Data/PositionerScripts.rxdata
https://drive.google.com/uc?export=download&id=0B4Pi8i4pFhL-c01MV1I2dFJGazA,EliteBattle_0